### ISSUE TITLE
CONFIG_USE_CACHE

### ISSUE THREAD

**Issue by pana1990** [sidekit/config#4]
When i set CONFIG_USE_CACHE to 1, i have the following error : 

![screenshot_1](https://cloud.githubusercontent.com/assets/6630197/26124862/52a5b2ca-3a80-11e7-9bce-39d8ea83f9d4.png)

This happen because Config class generate the following cache when i use anonymous function in my configuration : 

```php 
 array (
        'User' => 'app\models\User',
      ),
      'on beforeAction' => 
      Closure::__set_state(array(
      )),
```

// my config 
```php
'on beforeAction' => function() {
        \Yii::$app->setComponents([
            'assetManager' => [
                'class' => 'yii\web\assetManager',
                'bundles' => [
                    'yii\\web\\YiiAsset' => [
                        'sourcePath' => '@yii/assets',
                        'js' => [
                            'yii.js'
                        ]
                    ]
                ]
            ]
        ]);
    }
```

Any idea to fix issue?

**Comment by tonydspaniard** [comment]
@pana1990 I suggest you remove that application event from the config file and add it to the bootstrapping process: http://www.yiiframework.com/doc-2.0/guide-structure-applications.html#application-events

**Comment by tonydspaniard** [comment]
@pana1990 what i do is have an `events.php` where i have my events, here is an example of User Module: 

```php 
Event::on(
    AdminController::class,
    UserEvent::EVENT_AFTER_CREATE,
    function () {
        UrlHelper::redirectTo(['/user/admin/index']);
    }
);
```

You can actually use any event (application events for example), and include the file on your bootstrap process. You don't need to mix closures with configuration files.

**Comment by SerikK** [comment]
I have the same error
But I do
'on afterOpen' => function($event) {
        $event->sender->createCommand("SET time_zone='+00:00';")->execute();
    },
    
    So how to refactor that?
