### ISSUE TITLE
How to set global params

### ISSUE THREAD

**Issue by skiiiks** [sidekit/config#7]
Hi:
You load the params creating an array per file located in "params" directory.
That collides with some plugins that usually read some configuration in the "params" main array, for example, GridView of Kartik uses this:

```
$this->bsDependencyEnabled = ArrayHelper::getValue(Yii::$app->params, 'bsDependencyEnabled', true);
```

and if I created a file in the params directory called gridview with this information

```
return [
    'bsDependencyEnabled' => false
];
```
the settings is in Yii::$app->params["gridview"] and not in Yii::$app->params

So, with configkit, where do you recommend to put "global" params in order to use them for some plugins compatibilities ?

thank you

**Comment by marcinl26** [comment]
Idk if its right place but my research drove me into file `app.php` placed in `config/web` directory (`console `or `test `whatever environment you working on).  I've added there `params` key. Below example of global param used by mentioned Kartik widgets.
**Example of config/web/app.php**:
```
...
'language' => Configuration::env()->get('APP_LANGUAGE'),
'bootstrap' => ['log'],
'params'=>[
        'bsVersion' => '4.x'
    ],
...
```

**Comment by paskuale75** [comment]
I don't know why but to me the language parameter always remains on "en" despite having set "it" in the .env file
[solved] must stop and restart `composer start-serve`

**Comment by tonydspaniard** [comment]
I would add it to the correspondent `app.php` file
